version: "3.3"
name: "BowlingDemo"
# Servidor nginx
services:
  # Configuración de php-fpm
  php-fpm:
    build:
      dockerfile: Dockerfile
    image: php:8-fpm
    container_name: "phpfpm-bownling"
    volumes:
      - ./:/var/www/html/
